### PR TITLE
Dual red objects

### PR DESCRIPTION
**Pull request by blowfish880**
Rewrite the dual (hybrid) attack taking advantage of the new `short_vectors` feature of the reduction module.

### CODE REVIEW

**Comment by malb** [comment]
Just as a sanity check, did you compare ADPS16 before and after and the results match?

**Comment by blowfish880** [comment]
Good call. They don't. I'll try to figure out what's going on.

**Comment by blowfish880** [comment]
Ah, I think I found it. It's a bug in [the previous version](https://github.com/malb/lattice-estimator/blob/main/estimator/lwe_dual.py#L143), it's taking `rho=4/3` instead of the square root. When changing that the results match.

**Comment by malb** [comment]
Woohoo

**Pull request merged**
